#!/usr/bin/env python3
"""Put each chapter's agent art into its Drive folder.

Every chapter gets an `Agents/` folder holding:

* **its own agent** — hue, action, ridge and mirror all derived from a hash of
  the chapter's own name, per the design system's chapter-plate rule, so a
  chapter renders the same scene every time and neighbours never match; and
* **the ten generic agents** — the same motif in each spectrum hue, doing
  nothing in particular, for an empty state, a divider or a loading frame.

All of them are animated GIFs: the agent bobs by one grid unit and blinks once
per loop. That is the whole of the motion the design system licenses here —
"constant-speed and small", no bounces, no springs — and it is why these encode
as small flat-art GIFs rather than needing video.

The art is generated by `aaif_events.agent_art`, which draws from
`design/aaif-tokens.css`, so an agent cannot drift off-palette. Build it first:

    python3 -c "import sys; sys.path.insert(0,'lib'); \\
        from aaif_events import agent_art as a; \\
        a.build_agents('/tmp/agents', ['Boston','Tokyo'], verbose=True)"

Read-only by default. Re-running is a no-op: a file whose bytes already match
is skipped, so this can be run after adding a chapter to fill in just that one.

**`create_chapter.py` does NOT do this.** A new chapter is cloned from
TemplateCity, and cloning would give it TemplateCity's agent rather than its
own — the art has to be derived from the new chapter's name. Run this after
creating a chapter; a full run reports which chapters are missing their agent,
so a forgotten one shows up rather than staying invisible.

Usage:
  python3 upload_agents.py --art /tmp/agents              # plan
  python3 upload_agents.py --art /tmp/agents --write
  python3 upload_agents.py --art /tmp/agents --chapter Boston --write
"""
import argparse
import hashlib
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import create_chapter as cc      # noqa: E402
import restyle_design_system as rd   # noqa: E402

AGENTS_FOLDER = "Agents"
GIF = "image/gif"
#: The ten generic agents, shared by every chapter.
GENERIC_RE = re.compile(r"^Agent \d\d\.gif$")


def chapters():
    """[(id, name)] for every chapter folder, sorted."""
    for k in cc.list_children(rd.COMMUNITY_ROOT):
        if k["name"] == rd.CHAPTERS_FOLDER:
            return sorted(((c["id"], c["name"]) for c in cc.list_children(k["id"])
                           if c["mimeType"] == cc.FOLDER), key=lambda t: t[1])
    return []


def _digest(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def art_for(art_dir, name):
    """[(filename, local path)] this chapter should hold."""
    safe = re.sub(r"[^\w .,-]", "_", name)
    want = []
    own = os.path.join(art_dir, "%s Agent.gif" % safe)
    if os.path.exists(own):
        want.append((os.path.basename(own), own))
    for f in sorted(os.listdir(art_dir)):
        if GENERIC_RE.match(f):
            want.append((f, os.path.join(art_dir, f)))
    return want


def sync_chapter(chapter_id, name, art_dir, write, tmpdir):
    """(name, uploaded, skipped, error). Idempotent: a file whose bytes already
    match is left alone, so a re-run after adding one chapter touches only it."""
    want = art_for(art_dir, name)
    if not any(f.endswith(" Agent.gif") for f, _p in want):
        return name, [], [], "no agent art generated for this chapter"
    try:
        kids = cc.list_children(chapter_id)
        folder = next((k for k in kids if k["name"] == AGENTS_FOLDER
                       and k["mimeType"] == cc.FOLDER), None)
        if folder is None:
            if not write:
                return name, [f for f, _p in want], [], None
            folder_id = cc.create_folder(AGENTS_FOLDER, chapter_id)
            existing = {}
        else:
            folder_id = folder["id"]
            existing = {k["name"]: k for k in cc.list_children(folder_id)}

        uploaded, skipped = [], []
        for fname, path in want:
            hit = existing.get(fname)
            if hit is not None:
                local = os.path.join(tmpdir, "cmp-%s.gif" % hit["id"])
                try:
                    cc.gws_download(hit["id"], local)
                    same = os.path.exists(local) and _digest(local) == _digest(path)
                finally:
                    if os.path.exists(local):
                        os.remove(local)
                if same:
                    skipped.append(fname)
                    continue
            if write:
                if hit is None:
                    meta = cc.gws_json(
                        "drive", "files", "create",
                        params={"supportsAllDrives": True, "fields": "id"},
                        body={"name": fname, "parents": [folder_id], "mimeType": GIF})
                    cc.gws_upload(meta["id"], path, GIF)
                else:
                    cc.gws_upload(hit["id"], path, GIF)
            uploaded.append(fname)
        return name, uploaded, skipped, None
    except Exception as e:
        return name, [], [], "%s: %s" % (type(e).__name__, str(e)[:200])


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--art", required=True, metavar="DIR",
                    help="Directory of generated agent GIFs")
    ap.add_argument("--write", action="store_true",
                    help="Actually create the folders and upload (default: plan)")
    ap.add_argument("--chapter", help="Only this chapter (exact name, case-insensitive)")
    ap.add_argument("--jobs", type=int, default=6)
    args = ap.parse_args()

    if not os.path.isdir(args.art):
        print("no such art directory: %s" % args.art)
        return 2
    generic = [f for f in os.listdir(args.art) if GENERIC_RE.match(f)]
    if len(generic) != 10:
        print("expected 10 generic agents in %s, found %d — regenerate the art"
              % (args.art, len(generic)))
        return 2

    todo = chapters()
    if args.chapter:
        todo = [(i, n) for i, n in todo if n.lower() == args.chapter.lower()]
    if not todo:
        print("no chapters matched.")
        return 1
    print("%d chapter(s); %d generic agent(s).%s\n"
          % (len(todo), len(generic),
             "" if args.write else "  PLAN ONLY — nothing will be written."))

    import tempfile
    uploaded = clean = failed = 0
    missing = []
    with tempfile.TemporaryDirectory() as tmpdir, \
            ThreadPoolExecutor(max_workers=args.jobs) as pool:
        for name, up, skip, err in pool.map(
                lambda t: sync_chapter(t[0], t[1], args.art, args.write, tmpdir), todo):
            if err:
                failed += 1
                missing.append((name, err))
                print("  FAILED  %s\n            %s" % (name, err))
            elif up:
                uploaded += 1
                print("  %s  %-26s %d file(s)"
                      % ("UPLOADED" if args.write else "would add", name, len(up)))
            else:
                clean += 1
    print("\n%d chapter(s) %s, %d already current, %d failed."
          % (uploaded, "updated" if args.write else "would be updated", clean, failed))
    if uploaded and not args.write:
        print("Re-run with --write to apply.")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
