#!/usr/bin/env python3
"""Put each chapter's icon set into its Drive folder.

Every chapter gets an `Icons/` folder holding:

* **its own agent** — hue, action, ridge and mirror all derived from a hash of
  the chapter's own name, per the design system's chapter-plate rule, so a
  chapter renders the same scene every time and neighbours never match; and
* **the ten generic agents** — the same motif in each spectrum hue, doing
  nothing in particular, for an empty state, a divider or a loading frame; and
* **the AAIF logos** — the lock-up in black and reverse and the square mark, as
  both SVG (the source, for print and for anything that scales) and PNG (for
  the places that will not take an SVG). The Linux Foundation Projects ribbon
  is deliberately NOT here: it is LF's mark rather than AAIF's, and shipping a
  hand-transcribed copy of another organisation's trademark into eighty folders
  is not something to do casually. Add it from the design system if it is
  wanted.
  They are here so an organizer reaching for a logo finds the right one in the
  same place as everything else, rather than pulling a stale copy off a slide.

The agents are animated GIFs: the agent bobs by one grid unit and blinks once
per loop. That is the whole of the motion the design system licenses here —
"constant-speed and small", no bounces, no springs — and it is why they encode
as small flat-art GIFs rather than needing video. The logos are static.

The art is generated by `aaif_events.agent_art`, which draws from
`design/aaif-tokens.css`, so an agent cannot drift off-palette. Build it first:

    python3 -c "import sys; sys.path.insert(0,'lib'); \\
        from aaif_events import agent_art as a; \\
        a.build_agents('/tmp/icons', ['Boston','Tokyo'], verbose=True); \\
        a.build_logos('/tmp/icons')"

Read-only by default. Re-running is a no-op: a file whose bytes already match
is skipped, so this can be run after adding a chapter to fill in just that one.

**`create_chapter.py` does NOT do this.** A new chapter is cloned from
TemplateCity, and cloning would give it TemplateCity's agent rather than its
own — the art has to be derived from the new chapter's name. Run this after
creating a chapter; a full run reports which chapters are missing their agent,
so a forgotten one shows up rather than staying invisible.

Usage:
  python3 upload_agents.py --art /tmp/agents              # plan
  python3 upload_agents.py --art /tmp/agents --write
  python3 upload_agents.py --art /tmp/agents --chapter Boston --write
"""
import argparse
import hashlib
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor
from typing import NamedTuple, Optional

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import create_chapter as cc      # noqa: E402
import restyle_design_system as rd   # noqa: E402

ICONS_FOLDER = "Icons"
GIF = "image/gif"
#: The ten generic agents, shared by every chapter.
GENERIC_RE = re.compile(r"^Agent \d\d\.gif$")
#: The AAIF logos, likewise shared. Matched by name so a chapter's own agent —
#: the only per-chapter file — is never mistaken for one of them.
LOGO_RE = re.compile(r"^AAIF .*\.(svg|png)$")

MIME_BY_EXT = {".gif": "image/gif", ".svg": "image/svg+xml", ".png": "image/png"}


def chapters():
    """[(id, name)] for every chapter folder, sorted."""
    for k in cc.list_children(rd.COMMUNITY_ROOT):
        if k["name"] == rd.CHAPTERS_FOLDER:
            return sorted(((c["id"], c["name"]) for c in cc.list_children(k["id"])
                           if c["mimeType"] == cc.FOLDER), key=lambda t: t[1])
    return []


def _digest(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def art_for(art_dir, name):
    """[(filename, local path)] this chapter should hold."""
    safe = re.sub(r"[^\w .,-]", "_", name)
    want = []
    own = os.path.join(art_dir, "%s Agent.gif" % safe)
    if os.path.exists(own):
        want.append((os.path.basename(own), own))
    for f in sorted(os.listdir(art_dir)):
        if GENERIC_RE.match(f) or LOGO_RE.match(f):
            want.append((f, os.path.join(art_dir, f)))
    return want


class Synced(NamedTuple):
    """What one chapter's `Icons/` folder needed.

    `uploaded` and `skipped` are both lists of filenames and were returned
    positionally next to each other, which is a swap waiting to happen — and
    the summary counts a chapter as clean on `not uploaded` alone, so a swap
    would report a whole estate as current while uploading nothing.

    `error` is beside them rather than raised: `sync_chapter` runs under a
    `ThreadPoolExecutor.map`, and one chapter's Drive failure must not take the
    other eighty down with it.
    """
    name: str
    #: Filenames sent (or, in a plan run, that WOULD be sent).
    uploaded: tuple = ()
    #: Filenames already byte-identical in Drive and left alone.
    skipped: tuple = ()
    error: Optional[str] = None


def sync_chapter(chapter_id, name, art_dir, write, tmpdir):
    """Bring one chapter's `Icons/` folder up to date. Returns a `Synced`.

    Idempotent: a file whose bytes already match is left alone, so a re-run
    after adding one chapter touches only it."""
    try:
        # Inside the try: `art_for` does an `os.listdir`, and an art directory
        # that vanishes or turns unreadable mid-run would otherwise raise
        # straight out through `pool.map` and abandon every chapter that had
        # not been reached yet — the exact failure this function returns its
        # error rather than raising in order to avoid.
        want = art_for(art_dir, name)
        if not any(f.endswith(" Agent.gif") for f, _p in want):
            return Synced(name, error="no agent art generated for this chapter")
        kids = cc.list_children(chapter_id)
        folder = next((k for k in kids if k["name"] == ICONS_FOLDER
                       and k["mimeType"] == cc.FOLDER), None)
        if folder is None:
            if not write:
                return Synced(name, uploaded=tuple(f for f, _p in want))
            folder_id = cc.create_folder(ICONS_FOLDER, chapter_id)
            existing = {}
        else:
            folder_id = folder["id"]
            existing = {k["name"]: k for k in cc.list_children(folder_id)}

        uploaded, skipped = [], []
        for fname, path in want:
            hit = existing.get(fname)
            if hit is not None:
                local = os.path.join(tmpdir, "cmp-%s.gif" % hit["id"])
                try:
                    cc.gws_download(hit["id"], local)
                    same = os.path.exists(local) and _digest(local) == _digest(path)
                finally:
                    if os.path.exists(local):
                        os.remove(local)
                if same:
                    skipped.append(fname)
                    continue
            mime = MIME_BY_EXT[os.path.splitext(fname)[1].lower()]
            if write:
                if hit is None:
                    meta = cc.gws_json(
                        "drive", "files", "create",
                        params={"supportsAllDrives": True, "fields": "id"},
                        body={"name": fname, "parents": [folder_id], "mimeType": mime})
                    cc.gws_upload(meta["id"], path, mime)
                else:
                    cc.gws_upload(hit["id"], path, mime)
            uploaded.append(fname)
        return Synced(name, tuple(uploaded), tuple(skipped))
    except Exception as e:
        # Never a bare str(): an exception whose str() is empty would be falsy
        # and main() would count the chapter as clean, printing nothing at all.
        return Synced(name, error="%s: %s" % (type(e).__name__, str(e)[:200]))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--art", required=True, metavar="DIR",
                    help="Directory of generated agent GIFs and logo files")
    ap.add_argument("--write", action="store_true",
                    help="Actually create the folders and upload (default: plan)")
    ap.add_argument("--chapter", help="Only this chapter (exact name, case-insensitive)")
    ap.add_argument("--jobs", type=int, default=6)
    args = ap.parse_args()

    if not os.path.isdir(args.art):
        print("no such art directory: %s" % args.art)
        return 2
    generic = [f for f in os.listdir(args.art) if GENERIC_RE.match(f)]
    if len(generic) != 10:
        print("expected 10 generic agents in %s, found %d — regenerate the art"
              % (args.art, len(generic)))
        return 2
    logos = [f for f in os.listdir(args.art) if LOGO_RE.match(f)]
    if not logos:
        print("no AAIF logos in %s — every chapter's Icons folder should hold "
              "them; see the module docstring." % args.art)
        return 2

    todo = chapters()
    if args.chapter:
        todo = [(i, n) for i, n in todo if n.lower() == args.chapter.lower()]
    if not todo:
        print("no chapters matched.")
        return 1
    print("%d chapter(s); %d generic agent(s); %d logo file(s).%s\n"
          % (len(todo), len(generic), len(logos),
             "" if args.write else "  PLAN ONLY — nothing will be written."))

    import tempfile
    uploaded = clean = failed = 0
    missing = []
    with tempfile.TemporaryDirectory() as tmpdir, \
            ThreadPoolExecutor(max_workers=args.jobs) as pool:
        for r in pool.map(
                lambda t: sync_chapter(t[0], t[1], args.art, args.write, tmpdir), todo):
            # `is not None`, not truthiness: `error` is a defaulted field now,
            # and an empty string would fall through to `else: clean += 1` —
            # the chapter counted "already current", nothing printed, exit 0.
            if r.error is not None:
                failed += 1
                missing.append((r.name, r.error))
                print("  FAILED  %s\n            %s" % (r.name, r.error))
            elif r.uploaded:
                uploaded += 1
                print("  %s  %-26s %d file(s)"
                      % ("UPLOADED" if args.write else "would add", r.name,
                         len(r.uploaded)))
            else:
                clean += 1
    print("\n%d chapter(s) %s, %d already current, %d failed."
          % (uploaded, "updated" if args.write else "would be updated", clean, failed))
    # The module docstring promises "a full run reports which chapters are
    # missing their agent, so a forgotten one shows up rather than staying
    # invisible". `missing` was collected and never read, so that summary did
    # not exist — the inline FAILED lines scroll past in an eighty-chapter run,
    # which is exactly when the promise matters.
    if missing:
        print("\nCHAPTERS NEEDING ATTENTION (%d):" % len(missing))
        for name, why in sorted(missing):
            print("  - %-26s %s" % (name, why))
        no_art = [n for n, why in missing if why.startswith("no agent art")]
        if no_art:
            print("\n%d of these have no generated agent. Rebuild the art for "
                  "them before re-running:\n  %s"
                  % (len(no_art), ", ".join(sorted(no_art))))
    if uploaded and not args.write:
        print("Re-run with --write to apply.")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
